Repository ts-graphviz/ts-graphviz, pull requests merged in 2020-01, with the labels that each got.

#35 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#34 Support compass port
  src/__test__/__snapshots__/usecase.spec.ts.snap
  src/__test__/usecase.spec.ts
  src/model/Node.ts
  src/model/cluster/Cluster.ts
  src/utils/dot-rendering.ts
Labels: enhancement

#36 Refacter and document comment
  src/__test__/__snapshots__/usecase.spec.ts.snap
  src/common/abstract.ts
  src/common/index.ts
  src/common/interface.ts
  src/common/type.ts
  src/common/util.ts
  src/model/Attributes.ts
  src/model/Context.ts
  src/model/Edge.ts
  src/model/ID.ts
  src/model/Node.ts
  src/model/__test__/Edge.spec.ts
  src/model/__test__/ID.spec.ts
  src/model/__test__/__snapshots__/ID.spec.ts.snap
  src/model/cluster/Cluster.ts
  src/model/cluster/Digraph.ts
  src/model/cluster/Graph.ts
  src/model/cluster/__test__/Digraph.spec.ts
  src/model/cluster/__test__/Graph.spec.ts
  src/model/cluster/__test__/Subgraph.spec.ts
  src/model/cluster/__test__/__snapshots__/Digraph.spec.ts.snap
  src/model/cluster/__test__/__snapshots__/Graph.spec.ts.snap
  src/model/cluster/__test__/__snapshots__/Subgraph.spec.ts.snap
  src/model/index.ts
  src/usecase.ts
Labels: documentation

#37 Add attributes APIs
  src/model/Attributes.ts
  src/model/AttributesBase.ts
  src/model/__test__/Attributes.spec.ts
  src/model/__test__/__snapshots__/Attributes.spec.ts.snap
  src/model/cluster/Cluster.ts
  src/model/cluster/__test__/Digraph.spec.ts
  src/model/cluster/__test__/Graph.spec.ts
  src/model/cluster/__test__/Subgraph.spec.ts
  src/model/cluster/__test__/__snapshots__/Digraph.spec.ts.snap
  src/model/cluster/__test__/__snapshots__/Graph.spec.ts.snap
  src/model/cluster/__test__/__snapshots__/Subgraph.spec.ts.snap
Labels: enhancement

#41 Type abstraction by interface
  src/__test__/usecase.spec.ts
  src/abstract.ts
  src/common/index.ts
  src/common/interface.ts
  src/common/type.ts
  src/common/util.ts
  src/index.ts
  src/model/Attributes.ts
  src/model/AttributesBase.ts
  src/model/Cluster.ts
  src/model/Context.ts
  src/model/Digraph.ts
  src/model/Edge.ts
  src/model/Graph.ts
  src/model/ID.ts
  src/model/Node.ts
  src/model/RootCluster.ts
  src/model/Subgraph.ts
  src/model/__test__/Attributes.spec.ts
  src/model/__test__/Context.spec.ts
  src/model/__test__/Digraph.spec.ts
  src/model/__test__/Edge.spec.ts
  src/model/__test__/Graph.spec.ts
  src/model/__test__/Node.spec.ts
  src/model/__test__/Subgraph.spec.ts
  src/model/__test__/__snapshots__/Digraph.spec.ts.snap
  src/model/__test__/__snapshots__/Graph.spec.ts.snap
  src/model/__test__/__snapshots__/Subgraph.spec.ts.snap
  src/model/cluster/Cluster.ts
  src/model/cluster/index.ts
  src/model/index.ts
  src/types.ts
  src/usecase.ts
Labels: enhancement

#42 Add PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/settings.json
Labels: documentation

#44 Add types field to package.json
  package.json
Labels: documentation

#47 Add attribute types
  src/attribute.ts
  src/index.ts
  src/model/Attributes.ts
  src/model/AttributesBase.ts
  src/model/Cluster.ts
  src/model/Context.ts
  src/model/Edge.ts
  src/model/Node.ts
  src/model/RootCluster.ts
  src/model/Subgraph.ts
  src/model/__test__/Attributes.spec.ts
  src/model/__test__/Subgraph.spec.ts
  src/model/__test__/__snapshots__/Subgraph.spec.ts.snap
  src/types.ts
Labels: enhancement

#64 fix: use quote for IDs
  README.md
  src/__test__/__snapshots__/usecase.spec.ts.snap
  src/__test__/usecase.spec.ts
  src/model/ID.ts
  src/model/__test__/__snapshots__/Attributes.spec.ts.snap
  src/model/__test__/__snapshots__/Digraph.spec.ts.snap
  src/model/__test__/__snapshots__/Edge.spec.ts.snap
  src/model/__test__/__snapshots__/Graph.spec.ts.snap
  src/model/__test__/__snapshots__/Node.spec.ts.snap
  src/model/__test__/__snapshots__/Subgraph.spec.ts.snap
Labels: bug, good first issue

#66 Upgrade to jest25
  .github/workflows/node-ci.yml
  package.json
  yarn.lock
Labels: dependencies

#67 Add CONTRIBUTING.md
  .npmignore
  CONTRIBUTING.md
  README.md
Labels: documentation
