Repository ts-graphviz/ts-graphviz, pull requests merged in 2020-05, with the labels that each got.

#150 Add grouped edge target
  src/model/__tests__/clusters.spec.ts
  src/model/clusters.ts
  src/model/edges.ts
  src/model/nodes.ts
  src/render/__tests__/__snapshots__/edges.spec.ts.snap
  src/render/__tests__/edges.spec.ts
  src/render/renderer.ts
  src/render/utils.ts
  src/types.ts
  tsconfig.json
Labels: enhancement

#154 add attribute undefined value validation
  src/model/attributes-base.ts
  src/render/__tests__/__snapshots__/attributes.test.ts.snap
  src/render/__tests__/attributes.test.ts
Labels: bug

#156 typescript errors in README
  README.md
Labels: documentation
