Repository ts-graphviz/ts-graphviz, pull requests merged in 2022-12, with the labels that each got.

#732 test: add e2e testing
  .github/workflows/node-ci.yml
  .npmignore
  e2e/.gitignore
  e2e/envs/cjs/package.json
  e2e/envs/cjs/sample.js
  e2e/envs/esm/package.json
  e2e/envs/esm/sample.js
  e2e/package.json
Labels: enhancement

#712 feat: add adapter module
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/node-ci.yml
  .npmignore
  .vscode/settings.json
  README.md
  README_ja.md
  e2e/.gitignore
  e2e/envs/cjs/package.json
  e2e/envs/deno/.gitignore
  e2e/envs/deno/package.json
  e2e/envs/deno/patch-package.sh
  e2e/envs/esm/package.json
  e2e/main.ts
  e2e/package.json
  e2e/tsconfig.json
  media/adapter-state-machine.dot
  media/adapter-state-machine.svg
  package.json
  rollup.config.js
  src/adapter/deno/mod.d.ts
  src/adapter/deno/mod.js
  src/adapter/index.ts
  tsconfig.build.json
  tsconfig.json
  typedoc.json
Labels: enhancement

#738 doc: add who's using list
  README.md
  README_ja.md
Labels: documentation

#751 Update package.json
  package.json
Labels: bug
